name: build-test
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable && corepack prepare pnpm@9 --activate
      - run: pnpm install
      - run: pnpm run typecheck
      - run: pnpm run test:ci
