name: CI

on:
  push:
    branches: [ main, release/**, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test --silent

      - name: Build
        run: npm run build
