name: Deploy DB to Supabase
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'supabase/sql/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply migrations to Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -e
          for f in $(find supabase/sql -maxdepth 1 -type f -name '*.sql' | sort); do
            echo "Applying $f"
            psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
      - name: Sanity check (RLS still ON)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$SUPABASE_DB_URL" -c "select table_schema, table_name, row_security_active from information_schema.tables where table_schema in ('core','sec','omni','sch','crm');"
